### ISSUE TITLE
[Question] How is persistence handled?

### ISSUE THREAD

**Issue by denisinla** [keen-studio/react-wp-rest#7]
Played a bit with your stack and noticed that theres no data persistence when using docker. Was this intentional?

**Comment by jmikrut** [comment]
There should be!  Depends on how you use it.  If you run `docker-compose stop` and `docker-compose start` everything should pick right back up where you left off.  Does it not in your situation?

Are you potentially using multiple instances of this repo at the same time, but maybe the names of your containers are the same within your `docker-compose.yml`?

**Comment by denisinla** [comment]
Just ran a few tests and doesn't look like its doing so. The db container just pulls mariadb but no persistence is available for it. Perhaps using the below:

```
volumes:
  wp_db_data:
    driver: local

wp_db:
  image: mariadb
  volumes:
    - db_data:/var/lib/mysql
```
